apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineops-web
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: cicd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: cicd
    notifications.argoproj.io/subscribe.on-sync-running.slack: cicd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: cicd
    notifications.argoproj.io/subscribe.on-deployed.slack: cicd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: cicd
spec:
  selector:
    matchLabels:
      app: mineops-web
  replicas: 2
  template:
    metadata:
      labels:
        app: mineops-web
    spec:
      containers:
        - name: mineops-web
          image: chogudwns/mineops:45
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
