apiVersion: v1
kind: Service
metadata:
  name: mineops-web
  labels:
    app: mineops-web
spec:
  type: LoadBalancer
  selector:
    app: mineops-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
